title: Will Anderson
email: wmaxand@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Will Anderson is a Product Designer that lives in Brooklyn, NY. 
  He works at Instagram. 
url: https://willanderson.xyz/
# baseurl: /willanderson.xyz/


# Build settings
plugins:
  - jekyll-postcss-v2
postcss:
  cache: false
collections:
  projects:
    output: true
  work:
    output: true
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project-detail"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
