# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/images'
collections:
  - name: 'projects'
    label: 'Projects'
    folder: '_projects/'
    editor:
      preview: false
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Company', name: 'company', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }      
      - { label: 'Hero', name: 'hero', widget: 'image' }
      - { label: 'Preview', name: 'preview', widget: 'string' }
      - { label: 'Introduction', name: 'intro', widget: 'markdown' }
      - label: 'Items'
        name: 'items'
        widget: 'list'
        fields:
          - { label: 'Asset', name: 'asset', widget: 'image', required: false }
          - { label: 'Background', name: 'bg', widget: 'image', required: false }
          - { label: 'Caption', name: 'text', widget: 'text', required: false }
 
 

