# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/images'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
  - name: 'projects'
    label: 'Projects'
    folder: '_projects/'
    create: true
    fields:
      - { name: Title }