# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/images'
collections:
  - name: 'projects'
    label: 'Projects'
    folder: '_projects/'
    editor:
      preview: false
    create: true
    fields:
      - { label: 'status', name: 'status', widget: 'select', options: ["Preview", "Published"] }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Company', name: 'company', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }      
      - { label: 'Hero', name: 'hero', widget: 'image' }
      - { label: 'Hero Style', name: 'hero_style', widget: 'select', options: ["background", "centered"], default: "centered" }
      - { label: 'Preview', name: 'preview', widget: 'string' }
      - { label: 'Introduction', name: 'intro', widget: 'markdown' }
      - label: 'Items'
        name: 'items'
        widget: 'list'
        fields:
          - { label: 'Style', name: 'media_style', widget: 'select', options: ["background", "centered"], default: "centered" }
          - { label: 'Asset', name: 'asset', widget: 'image', required: false }
          - { label: 'Background', name: 'bg', widget: 'image', required: false }
          - { label: 'Caption', name: 'text', widget: 'text', required: false }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    create: true
    files: 
      - label: 'About'
        name: 'about'
        file: 'about.md'    
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Intro', name: 'intro', widget: 'markdown' }
          - label: 'CV'
            name: 'cv'
            widget: 'list'
            fields:
              - { label: 'Company', name: 'company', widget: 'string', required: true }
              - { label: 'Title', name: 'title', widget: 'string', required: true }
              - { label: 'Year', name: 'year', widget: 'string', required: true }
              - { label: 'Location', name: 'location', widget: 'string', required: true }
              - { label: 'Url', name: 'url', widget: 'string', required: true }
              - { label: 'Description', name: 'description', widget: 'text', required: true }
              

 

